services:
  - type: web
    name: photo-geolocator
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PRODUCTION
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CLOUD_PROJECT
        value: photogeo-447004
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: photo-geolocator-cache
          property: connectionString
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true

  - type: redis
    name: photo-geolocator-cache
    ipAllowList: []
    plan: free
